### ISSUE TITLE
fix tests on Windows

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#105]
![image](https://cloud.githubusercontent.com/assets/89685/24399988/0e58596c-13af-11e7-9d4a-83bfd94676dd.png)

**Comment by slayoo** [comment]
to enable execution of the tests, lines with "test_all" in appveyor.yml need to be uncommented

**Comment by tvatter** [comment]
What about the other tests?

Those might be related to the NLopt install...
