### ISSUE TITLE
fix warning on Windows

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#107]
both 32-bit and 64-bit builds:
- [ ] test\src_test/include/test_vinecop_class.hpp(64): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data 
- [ ] test\src_test/include/test_vinecop_class.hpp(91): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data

64-bit build:
- [ ] src\bicop\tll0.cpp(56): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\bicop\tools_bicopselect.cpp(17): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(49): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(50): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(125): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(126): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(443): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_interpolation.cpp(491): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_stats.cpp(63): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_stats.cpp(116): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\misc\tools_stats.cpp(136): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\rvine_matrix.cpp(16): warning C4244: '=': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\rvine_matrix.cpp(41): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\rvine_matrix.cpp(148): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(31): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(42): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(93): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(104): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(105): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data 
- [ ] src\vinecop\tools_structselect.cpp(131): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(132): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(211): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\tools_structselect.cpp(233): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data 
- [ ] include\misc/tools_stl.hpp(54): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(43): warning C4244: '=': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(64): warning C4244: '=': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(102): warning C4244: '=': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(116): warning C4244: '=': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(150): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(188): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(207): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(269): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(309): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(310): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(465): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data 
- [ ] src\vinecop\class.cpp(466): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(605): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(609): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] src\vinecop\class.cpp(690): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
- [ ] test\src_test\vinecop_test.cpp(21): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data 
- [ ] test\src_test\vinecop_test.cpp(22): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data

**Comment by tnagler** [comment]
fixed, see  #121
