### ISSUE TITLE
git_revision.hpp does not get installed with "make install"

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#108]
![image](https://cloud.githubusercontent.com/assets/89685/24402956/3075c186-13bb-11e7-85c6-711921806828.png)

**Comment by slayoo** [comment]
https://github.com/vinecopulib/vinecopulib/pull/117

**Comment by tvatter** [comment]
Can we close then?

**Comment by slayoo** [comment]
yes!
