### ISSUE TITLE
enable install target for Windows

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#110]
All install() commands are in an if-not-windows block as of now (https://github.com/vinecopulib/vinecopulib/blob/724bd604b620f075906e065f9517392ea705c7b4/cmake/buildTargets.cmake#L39)

Execution of the installation on Windows can be done with:
```
cmake --build . --config Release --target install
```

**Comment by tvatter** [comment]
Yes, the reason is that I don't know anything about how to set-up an install in a windows environment.

**Comment by slayoo** [comment]
Let's just first try if it works :)
https://github.com/vinecopulib/vinecopulib/pull/120

**Comment by slayoo** [comment]
worked: https://ci.appveyor.com/project/vinecopulib/vinecopulib/build/1.0.37/job/qi4n3dlsrsxrm3l3#L1530
#120 ready for merging
