### ISSUE TITLE
github release tag for 0.0

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#116]
Github has its "release" mechanism. Currently, it shows no releases for vinecopulib:

![image](https://cloud.githubusercontent.com/assets/89685/24445420/1943eed4-146a-11e7-9962-6311654207a0.png)

This can be achieved by tagging a commit. Before doing it, I suggest committing the git_revision.hpp file, so it will be present in the zip/tarball downloadable by the users. After releasing the file can be removed from the repo (it is autogenerated by CMake for users obtaining the library via git).

**Comment by tnagler** [comment]
Yeah I didn't want to create a release with broken links in the README, will make one for 0.0.1

**Comment by slayoo** [comment]
0.0.1 has the relase tag, closing
