### ISSUE TITLE
0.0.1 tarball does not ship with git_revision.hpp -> "make install" will fail

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#124]

**Comment by tvatter** [comment]
In windows?

**Comment by slayoo** [comment]
on all platforms

**Comment by tvatter** [comment]
I thought that we wanted to exclude git_revision.hpp from the commits, so I added it to gitignore.

What should we do?

**Comment by tvatter** [comment]
And with the current version, "make install" is working on my machine btw...

**Comment by slayoo** [comment]
Yes, the git_revision.hpp would best be excluded from commits, but it needs to be shipped in the .zip and .tar.gz release files to make "make install" be able to copy it to system directories for users that didn't use git to obtain the library.

I suggest just adding these files to the .zip and .tar.gz release archives.

**Comment by tnagler** [comment]
I think the the source .zip and .tar.gz are actually created automatically from github.

**Comment by tnagler** [comment]
And isn't the fit revision file created automatically by CMake?

**Comment by tvatter** [comment]
Yes, but only if it finds the .git folder, which is not included in the tarball...

**Comment by tvatter** [comment]
As said before, I'm against using this "hack" to manage the versions. I think that even in the age of git, we should use the master branch for pyvinecopulib and rvinecopulib, and control releases to master "manually" by increasing the major/minor/patch number whenever appropriate.

**Comment by slayoo** [comment]
For the record, I'm just suggesting things, and will not take part in the decision processes here :)

**Comment by tvatter** [comment]
Well, if Thomas and you think that we should keep using it, I'll gladly oblige, but if the decision was only mine,  I would have removed it long ago ;)

**Comment by tnagler** [comment]
OK, since this is causing us so much pain and we have actual versions we can refer to now, I think we can remove the revision thing.

**Comment by slayoo** [comment]
I'll comment it out tomorrow

**Comment by slayoo** [comment]
https://github.com/vinecopulib/vinecopulib/pull/135

**Comment by tnagler** [comment]
fixed by #135
