### ISSUE TITLE
build example programs in Appveyor

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#127]

**Comment by tvatter** [comment]
Agreed, although we probably need to solve the tests that fail first ;)

**Comment by slayoo** [comment]
Building the test program will test the "install" target
https://github.com/vinecopulib/vinecopulib/pull/150

**Comment by tvatter** [comment]
Do we know why we can compile and install but not run anything on windows?

**Comment by slayoo** [comment]
no

**Comment by tvatter** [comment]
OK, so, I've been looking at the appveyor logs from when you tried running main.exe:

https://ci.appveyor.com/project/vinecopulib/vinecopulib/build/1.0.146/job/mwffqa9nl5m0llym

Similarly as the tests that were failing, it looks like there is a problem with the fits. In my opinion, the most likely issue is that the linking to NLopt is not done properly.

We have two solutions:

a) Fix the NLopt issue
b) Switch to another optimizer

Given the issues with installing NLopt on windows (which needs to be done manually, hence it will be an issue for e.g. "non-experienced" R users), Thomas and I started to experiment with solution b).

**Comment by slayoo** [comment]
Perhaps this might be of some help then:
https://github.com/tnagler/VineCopula/pull/30

**Comment by tvatter** [comment]
I tried CppNumericalSolvers, but the implementation seems to be of poor quality (e.g. it was working for the Gaussian but it took forever to converge for the degrees of freedom of the t copula).

Thomas tried dlib, but he encountered similar convergence issues.

**Comment by slayoo** [comment]
re non-experienced R users on windows: aren't they going to get vinecopulib-R pre-compiled?

**Comment by tvatter** [comment]
That's a very good remark ;)

I think that it's Thomas who was considering this as an issue, so he may be more qualified than me to answer this.

**Comment by tnagler** [comment]
That's actually an excellent remark! They probably will be able to install from CRAN (because it's pre-compiled), just not from github or a source. So it's not as bad as I initially thought :)

**Comment by tvatter** [comment]
OK, so I guess we'll try a) then.

**Comment by slayoo** [comment]
Just an update: I was trying today to figure out the problem, and switched from pre-built nlopt package to building from sources. The nlopt build works, but all tests fail what seems to confirm the problem is not in vinecopulib: https://ci.appveyor.com/project/vinecopulib/vinecopulib/build/1.0.174

**Comment by slayoo** [comment]
Correcting the above - it was just a library path issue. Sorry.
All nlopt tests pass correctly on Appveyor: https://ci.appveyor.com/project/vinecopulib/vinecopulib/build/1.0.177

**Comment by slayoo** [comment]
OK, got a bit further with debugging it on Windows, the error occurs within nlopt's myvfunc() function when it calls bicop::pdf() which in turn errs within tools_stats::qnorm(u) in the line:

```
return x.unaryExpr([&dist](double y) {return boost::math::quantile(dist, y);});
```

**Comment by slayoo** [comment]
The contents of x above seem be uninitialised...

**Comment by tnagler** [comment]
Hm, this is really weird. I was looking through the code (on my phone) and can't see how that happens. Will check again later when I'm home.

**Comment by slayoo** [comment]
perhaps we could work together via Skype sharing the screen with the Windows debugger?

**Comment by slayoo** [comment]
![image](https://cloud.githubusercontent.com/assets/89685/25805895/aaafb842-3401-11e7-81db-106e13a7fa28.png)

Here's an example screenshot from the Visual Studio debugger showing that newdata->U in mle_objective contains some garbage (-1.45e+144 in this case)

**Comment by slayoo** [comment]
other members of newdata seem OK

**Comment by slayoo** [comment]
not sure if that's the actual problem, but here's something fishy going on in line 56 of parametric.cpp:

![image](https://cloud.githubusercontent.com/assets/89685/25806443/752ad5e2-3403-11e7-8683-463a37f5fb87.png)

The temp_data on the right-hand side is a 5000x1 array with finite values.
The my_data.U on the left is a 5000x2 array with uninitialised values.

**Comment by slayoo** [comment]
OK, following yesterday's fix (https://github.com/slayoo/vinecopulib/commit/cd155fd8ca33fc8b177a223b2ebccbf1f382296b#diff-13f7509874de8780a03d450c155f6101) most of the tests are fixed.

Trying to debug the remaining ones I've came across some garbage values in GaussianBicop::pdf in gaussian.cpp:

![image](https://cloud.githubusercontent.com/assets/89685/25840448/20c010aa-349c-11e7-941b-baea519bb262.png)

Variable tmp contains uninitialised data?

**Comment by slayoo** [comment]
Perhaps that's the same problem? qnorm() is defined to return Eigen::MatrixXd, while its output is assigned to Matrix<double, Dynamic, 2>

**Comment by slayoo** [comment]
No, L(1,0) in the above screenshot is uninitialised!

**Comment by tvatter** [comment]
L(1,0) = 0;

**Comment by slayoo** [comment]
Yeah: https://github.com/vinecopulib/vinecopulib/pull/169/files#diff-c4e9829158827e125e451354fabed985
Should be ready for merging soon (i.e., Travis and Appveyor builds in progress)
