### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#129]
We've been mentioning the idea of including serialization in order to be able to save/load objects from this library.

I've been exploring the possibilities and narrowed things to:

a) [Boost serialization](http://www.boost.org/doc/libs/1_63_0/libs/serialization/doc/)
b) [Cereal](http://uscilab.github.io/cereal/index.html)

Pros of a): we're already using Boost.
Cons of a): it's complex and arguably more importantly it doesn't seem to be header only (and hence not included in the BH R package).

Pros of b): simple, header only and there is a [Rcereal R package](https://cran.r-project.org/web/packages/Rcereal/index.html).
Cons of b): adding a new dependency.

Any thoughts?

**Comment by slayoo** [comment]
boost::property_tree::read_json() and boost::property_tree::write_json() could probably be used if we would target C++/R/Python interoperability?

**Comment by tvatter** [comment]
Does it work with polymorphism and smart pointers?

**Comment by slayoo** [comment]
well, we do not have neither polymorphism nor smart pointers in R or Python, so its off topic question... and of course it does not work with any kind of pointers :)

**Comment by slayoo** [comment]
(I mean we do not have polym. or smart pntr in vinecopulib bindings in R or Python)

**Comment by tvatter** [comment]
Yes, but we do in C++, and (arguably) the cleanest option to interface the library in R is to use Rcpp modules to expose directly the Bicop/Vinecop classes and their methods. Since Bicop objects contain smart pointers, I'm not sure how it would work with boost::property_tree...

**Comment by slayoo** [comment]
R (and Python and C++) code would need to recreate all bicop/vinecop objects based on the JSON file contents - nothing would be done automagically

**Comment by tvatter** [comment]
Understood.

Then what are the pros/cons of boost::property_tree (compared to boost serialization and cereal)?

**Comment by tvatter** [comment]
PS: In R, we're talking about ways of saving objects from session to session.

**Comment by slayoo** [comment]
- JSON is human readable
- no new dependency in C++
- header only
- available through BH R package, in Python bindings are already depend on Boost.Python

perhaps we could just add ctors to bicop and vinecop which accept a property tree, which we would load from json file using Boost in C++, Python and R?

**Comment by tvatter** [comment]
OK, then why not.

**Comment by tnagler** [comment]
I'm against boost serialization, the other two options are OK with me.

**Comment by tvatter** [comment]
OK, so I did have a look at boost::property_tree in more details, and I find this solution super tedious & "manual"  (e.g., you need to do a double loop to read/write a matrix).

It's not really an actual serialization library, since ones has to manually implementat the read/write of each object by telling which property you want to write/read.

By-the-way, Cereal also offers the possibility of saving in JSON format.

**Comment by tvatter** [comment]
See #205
