### ISSUE TITLE
move all stuff in misc into vinecopulib namespace?

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#130]
as of now, some code is within vinecopulib, and some within other namespaces - was it intentional?

**Comment by tvatter** [comment]
Yes, we were pondering between using sub-namespaces or additional namespaces, and we finally opted for the latter without really thinking about it.

Any thoughts?

**Comment by tnagler** [comment]
I think it makes sense to keep them in specific namespaces, we could make them sub-spaces though. The fact that `tools_interpolation` is part of the vinecopulib namespace is not intentional. I will change that.

**Comment by tvatter** [comment]
Specific namespaces definitely make sense, but shouldn't we switch to sub-namespaces?

**Comment by tnagler** [comment]
I'm OK with that.

**Comment by tnagler** [comment]
see #144
