### ISSUE TITLE
add Intel compiler run to travis

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#133]
https://github.com/nemequ/icc-travis

**Comment by tvatter** [comment]
Naïve question: is there a specific reason for prioritizing the Intel compiler?

I would have thought that CLANG was more common, but I'm still new to C++...

**Comment by slayoo** [comment]
prioritising - definitely not, but why not to test it
we compile with clang on OSX

**Comment by tvatter** [comment]
Yeah, I was thinking about clang on ubuntu, but intel is worth trying too.

**Comment by tvatter** [comment]
Alright, so I tried adding clang and icc, and I have the same (weird) problem related to the installation of the gsl R package:

https://travis-ci.org/vinecopulib/vinecopulib/jobs/231656854
https://travis-ci.org/vinecopulib/vinecopulib/jobs/231656857

**Comment by slayoo** [comment]
tried with using icc only for vinecopulib (and not the dependencies):
https://travis-ci.org/vinecopulib/vinecopulib/builds/232342874

Seems to run OK, but the compilation fails due to missing std::isnan

**Comment by tvatter** [comment]
Yes, I know, for both clang and icc, the problem is due to the install of the R package gsl.

**Comment by tvatter** [comment]
The isnan issue is corrected in https://github.com/vinecopulib/vinecopulib/tree/intel-compiler and the library and examples compile.

However, there is a weird segfault happening now :/ By weird, I mean that you need to look at `test_all.cpp` to see where the segfault happens.

**Comment by slayoo** [comment]
ran it through a debugger, but the stack trace doesn't reveal much (don't know how to force icc to emit debug symbols into the binary - -g seems not to work):

![image](https://cloud.githubusercontent.com/assets/89685/26107953/533ad4ac-3a4b-11e7-9851-476481809e9d.png)

**Comment by slayoo** [comment]
https://travis-ci.org/vinecopulib/vinecopulib/builds/232811099
