### ISSUE TITLE
should we have accessor methods for fit controls?

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#154]

**Comment by tnagler** [comment]
Besides `get_x` and `set_x`? Because we have those as far as I remember.

**Comment by slayoo** [comment]
Sorry, again too vague...

What I meant was:
- bicop::set_controls
- bicop::get_controls
- vinecop::set_controls
- vinceop::get_controls
(but, to be clear - I have no opinion, just asking)

**Comment by slayoo** [comment]
well... changed my mind: this would be useful in implementing tests for the ctors

**Comment by tnagler** [comment]
Ok now I understand. The controls are no data member so far and I don't think they should be (because they only make sense when `.fit()` or `.select()` is called.

**Comment by tvatter** [comment]
I concur with Thomas on this. Controls are external objects that you pass to constructor or the fit/select methods and have their own getters and setters. Unless the controls become data members of bicop/vinecop (and I don't think they should), there is no point in having a bicop::xxx_controls and vinecop::xxx_controls.

**Comment by slayoo** [comment]
I see your points, but it's hard to test the controls-accepting ctors... anyhow, closing for now.
