### ISSUE TITLE
std::endl instead of "\n" in error messages? (to make it work on Windows)

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#157]

**Comment by tnagler** [comment]
Oh, I didn't know that this was a problem. Then we should certainly change that.

**Comment by tvatter** [comment]
Won't there be a problem with Rcpp::Rcout ?

**Comment by tnagler** [comment]
`Rcpp::Rcout` accepts `std::endl` (see [here](http://dirk.eddelbuettel.com/blog/2012/02/18/)).

**Comment by tvatter** [comment]
See 7797769. I was only able to find "\n" in abstract.cpp, please tell me if I missed some.

**Comment by tnagler** [comment]
Pushed two more fixes for the example and README.
