### ISSUE TITLE
introduce "named parameters" instead of positional arguments in the API?

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#163]
We have now ctors with up to 9 positional parameters with default values. 
What about switching to something mimicking named parameters from other languages?
For example: https://isocpp.org/wiki/faq/ctors#named-parameter-idiom

**Comment by tvatter** [comment]
I like the idea. How ``standard'' is this particular approach? In https://marcoarena.wordpress.com/2014/12/16/bring-named-parameters-in-modern-cpp/, I noticed many ways to achieve essentially the same goal.

In any case, it seems that this approach is particularly well suited to our FitControlsBicop and FitControlsVinecop classes...

**Comment by tnagler** [comment]
Honestly: I think that's no longer going to happen. Close?

**Comment by slayoo** [comment]
Definitely :)
