### ISSUE TITLE
graded data transformation

### ISSUE THREAD

**Issue by bodashtart** [vinecopulib/vinecopulib#171]
If the passed graded data to the fitting includes 0 or 1, an overflow error will follow. There is validation for <0 and >1, but not in case of inequality. For ex.

>> Error in function boost::math::quantile(const normal_distribution<double>&, double): Probability argument is 1.2, but must be >= 0 and <= 1 !

So, thinking that adding validation around graded data including 0 and 1 would be helpful for end users of wrappers.

**Comment by tnagler** [comment]
This should be prevented by [`cut_and_rotate()`](https://github.com/vinecopulib/vinecopulib/blob/ba5e28dd95e3f54da2f057e03d80317b39d1faf8/src/bicop/class.cpp#L494) which is called internally by `Bicop::fit()`. What's the sepcific "use case" you have in mind?

**Comment by bodashtart** [comment]
I was working in the python wrapper. The error occurred when passing a matrix to the vinecop constructor that had 0's or 1's

>Error in function boost::math::erfc_inv<double>(double, double): Overflow Error

which seems to suggest that that the inverse of the normal cdf gets called before the cut_and_rotate takes care of 0's and 1's.

**Comment by tnagler** [comment]
Ah, good catch! I addressed this #173.
