### ISSUE TITLE
get rid of FindNloOpt.cmake?

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#172]
Nlopt's "make install" seems to install the filed needed to use find_package(nlopt):

![image](https://cloud.githubusercontent.com/assets/89685/25851863/c330c7dc-34c7-11e7-8ff8-39341a9fc749.png)

**Comment by tvatter** [comment]
It doesn't work locally on my machine, does it work on yours? And by looking at the picture you enclosed, how could find_package know how to look in e.g. nlopt-install?

**Comment by slayoo** [comment]
we use -DCMAKE_PREFIX_PATH="C:\projects\nlopt-install" in the appveyor script

**Comment by slayoo** [comment]
and I haven't checked yet if it works

**Comment by tvatter** [comment]
Can someone try on a linux machine? The fact that it does not work locally for me may be related to my brewed installation of NLopt...

**Comment by slayoo** [comment]
I confirm it worked for me locally.
Here's a pull request: https://github.com/vinecopulib/vinecopulib/pull/178

I've also submitted an issue for the Debian package asking to ship the *.cmake files in the .deb package:

For Homebrew, it seems that it is enough to use the build.head option to get the lib compiled with CMake and hence (I assume) get the *.cmake files installed: https://github.com/Homebrew/homebrew-science/blob/master/nlopt.rb

**Comment by tvatter** [comment]
OK, but the head version can be unstable and it's not always recommended or am I missing something?

**Comment by tvatter** [comment]
see #f720471

**Comment by tnagler** [comment]
On my new laptop (Linux Mint 18/Ubuntu 16.04), I get
```
▶ cmake ..
CMake Error at cmake/findNlopt.cmake:1 (find_package):
  By not providing "FindNLopt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NLopt", but
  CMake did not find one.

  Could not find a package configuration file provided by "NLopt" with any of
  the following names:

    NLoptConfig.cmake
    nlopt-config.cmake

  Add the installation prefix of "NLopt" to CMAKE_PREFIX_PATH or set
  "NLopt_DIR" to a directory containing one of the above files.  If "NLopt"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:11 (include)
```
`libnlopt0` and `libnlopt-dev` have been installed via `sudo apt-get install` in default locations:
```
$ whereis nlopt
nlopt: /usr/include/nlopt.hpp /usr/include/nlopt.f /usr/include/nlopt.h /usr/share/man/man3/nlopt.3.gz
```

**Comment by tnagler** [comment]
OK, I understand now that the library currently doesn't work with the debian package. I think we should've waited until nlopt ships with the cmake thing over debian, because this may take a year or never happen at all.

**Comment by slayoo** [comment]
for the record: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862390

**Comment by tvatter** [comment]
Not sure what the bugreport means... Will it be solved soon?

After thinking about it: if we need to use a hack for GCC6, cause problems for both linux and osx users, and don't get rid of findNLopt anyway, then I really don't see the point.

I'm pondering about a PR to reverse the change.

**Comment by tnagler** [comment]
I vote for reversing this change before a new release. As soon as the deb package ships with *.cmake, we can go back to the current behavior.

**Comment by slayoo** [comment]
I vote for supporting both - it would be strange to force users of the github version to downgrade.

**Comment by tnagler** [comment]
Yes, both is good!

**Comment by tvatter** [comment]
Why would the older code won't force the users of the github version to downgrade?

**Comment by slayoo** [comment]
You're right, sorry.

Anyhow, I think that doing a conditional statement:
```
find_package(NLopt)
if (found)
  gcc6_hack
else 
  load(cmake/findNLopt.cmake)
endif()
```

will give us the benefit of staying up to date with the github version (to be aware of such issues as the GCC-6 one).

**Comment by slayoo** [comment]
Also, to mention rationale behind using the github version - it is much easier to compile it on Windows because of CMake, and the pre-compiled package comes without the .lib files needed to link against nlopt.

**Comment by slayoo** [comment]
If bringing back the local findNLopt.cmake, let remember to rename the variables to match the ines in the github nlopt:

NLOPT_INCLUDE_DIR -> NLOPT_INCLUDE_DIRS

**Comment by tvatter** [comment]
In findNLopt.cmake, we have

#  NLOPT_INCLUDE_DIR - where to find nlopt.h
#  NLOPT_INCLUDE_DIRS - nlopt includes

**Comment by tvatter** [comment]
(NLOPT_INCLUDE_DIRS also contains NLOPT_INCLUDE_DIR)

**Comment by tvatter** [comment]
See #191
