### ISSUE TITLE
R-vine matrix notation

### ISSUE THREAD

**Issue by bodashtart** [vinecopulib/vinecopulib#174]
Is there a reason why the R-vine matrix notation in vinecopulib is different from the one in VineCopula? Asking since I'm assuming the VineCopula notation is the conventional one.

**Comment by tnagler** [comment]
Yes, see #48. 

So far there are at least three conventions: 
- the one used in most papers of TUMs research group, 
- the one in VineCopula (yes, this one is different and it makes no sense), 
- the one in Harry Joe's book. 

I discussed this new notation with Claudia Czado and my colleagues and all agreed that the  "vinecopulib-notation" is most reasonable.

**Comment by bodashtart** [comment]
I remember now that you may have mentioned this in Krakow. A different sort of a "memory" issue here :). The actual solution is quite neat, and well-documented - had I properly read the relevant section in the documentation I would not have asked the question.
