### ISSUE TITLE
make the README cover installation on Windows

### ISSUE THREAD

**Issue by asmaBNS** [vinecopulib/vinecopulib#175]

**Comment by asmaBNS** [comment]
Hello, may someone help me to load the vinecopulalib, I am new on Github and I would like to use it for a school project!
thanks in advance

**Comment by tvatter** [comment]
[The latest release](https://github.com/vinecopulib/vinecopulib/archive/v0.0.2.zip)

[The documentation to install](https://github.com/vinecopulib/vinecopulib#getting-started)

Let us know if it helps!

**Comment by asmaBNS** [comment]
In fact It has worked but the problem is that after reading the documentation to install, I did'nt know how to p^roceed step by step. Generally I don't use external libraries on Visual Studio C++ and I'll be thankful if someone clarify for me how to do step by step! once I install Cmake, Eigen and Nplot, how should I organize the source files/headers so that every thing works well 

Thank you very much

**Comment by tvatter** [comment]
Unfortunately, none of us is working with Windows, so a step by step guide for Visual Studio C++ is not something that we can currently provide.

[However, Slayoo managed to compile and run the unit tests on a Windows virtual machine.](https://github.com/vinecopulib/vinecopulib/blob/dev/appveyor.yml)

**Comment by slayoo** [comment]
Let's rename the issue to "make the README cover installation on Windows"

**Comment by slayoo** [comment]
Would this be useful: https://github.com/vinecopulib/vinecopulib/pull/188 ?

**Comment by slayoo** [comment]
Please reopen if anything more is needed.
Also, instructions for compiling the Python bindings on Windows are now in the master branch: https://github.com/vinecopulib/pyvinecopulib/blob/master/README.md
