### ISSUE TITLE
inverting functions using a method faster than bisection

### ISSUE THREAD

**Issue by bodashtart** [vinecopulib/vinecopulib#176]
In misc/tools_eigen.cpp, function inversion is computed by bisection. This may not introduce an overhead since the number of iteration is small (defaults to 35), but it may be a good idea to use a faster method. Slayoo pointed out that there are much faster methods available from boost:

http://www.boost.org/doc/libs/1_63_0/libs/math/doc/html/math_toolkit/roots/roots_noderiv.html

> bracket_and_solve_root functions use TOMS 748 algorithm by Alefeld, Potra and Shi that is asymptotically the most efficient known

For example 

```c++
template <class F, class T, class Tol>
std::pair<T, T>
   toms748_solve(
      F f,
      const T& a,
      const T& b,
      const T& fa,
      const T& fb,
      Tol tol,
      boost::uintmax_t& max_iter);
```
has a similary signature to invert_f. 

What do you guys think?

**Comment by tnagler** [comment]
Generally not a bad idea, but I'm not sure that using this function is going to be faster. Note that `invert_f()` finds the inverse of a function for many values simultaneously. We had an earlier version with a loop over individual inverses (which we would need to do with boost) and this was much slower. Could be worth trying, but wouldn't make it a priority as this mainly effects simulation.

**Comment by tvatter** [comment]
Is there a speed issue when doing simulations? 

If not, as mentioned by Thomas, I don't think that it is crucial to delve on this, since the inversion is not used in computationally intensive parts of the library.

**Comment by tnagler** [comment]
There's no issue, pdf is slower IIRC. So it should be more profitable to work on the first bullet in #69.

**Comment by tvatter** [comment]
I'm adding this to #69 and closing!
