### ISSUE TITLE
bicop_sanity_checks.select_can_handle_zeros_and_ones failed on Windows

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#179]
![image](https://cloud.githubusercontent.com/assets/89685/25991551/d3317922-3703-11e7-8047-d615a9669b62.png)

https://ci.appveyor.com/project/vinecopulib/vinecopulib/build/1.0.213/job/c50au4hrgkd6h0w9#L1827

**Comment by slayoo** [comment]
![image](https://cloud.githubusercontent.com/assets/89685/25995268/b8d7a4ee-3711-11e7-809d-14fe1404e6bc.png)


https://travis-ci.org/vinecopulib/vinecopulib/jobs/231503593#L7761

**Comment by tnagler** [comment]
I'm looking into it. It's a random failure and not related to what the unit test tries to check, but the small number of samples (10) it uses in `select()`. When I go down to 3 samples it throws an error in ~50% of the time.

**Comment by tnagler** [comment]
#180 solves this.
