### ISSUE TITLE
More options for setting seed for random number generator

### ISSUE THREAD

**Issue by bodashtart** [vinecopulib/vinecopulib#183]
Is there a specific reason to use a non-deterministic random number generator?

random_device in https://github.com/vinecopulib/vinecopulib/blob/ba5e28dd95e3f54da2f057e03d80317b39d1faf8/src/misc/tools_stats.cpp#L31

If not, then I think that adding different options for setting the seed, and adding an optional argument in places where rng is used may be a good idea. This is not a priority, but it would be useful for getting reproducible results (e.g. in simulations) which would make testing easier.

**Comment by tnagler** [comment]
No specific reason, didn't give it too much thought so far. Adding a seeding option is certainly a good idea!

**Comment by tvatter** [comment]
Now included in #282
