### ISSUE TITLE
Checks for the validity of an R-vine matrix

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/vinecopulib#186]
... should be added to the `RVineMatrix` class at some point.

**Comment by tvatter** [comment]
This is extremely weird, because the select function remove edges that are not allowed by the proximity condition. As such, constructors from data where no RVineMatrix is provided by the user should not return such a matrix.

However, the feature is indeed very important for user-provided matrices.

**Comment by tnagler** [comment]
Added checks in #192. 

@bodashtart: The checks are run whenever `RVineMatrix()` is called, in particular before `Vinecop(data)` returns the result. If there's an error on the C++ side, you will see an error message.

**Comment by tvatter** [comment]
Can we close it then?

**Comment by tnagler** [comment]
Yes, all fixed.
