### ISSUE TITLE
lcov dependency

### ISSUE THREAD

**Issue by NazBen** [vinecopulib/vinecopulib#199]
Hi,

It's not very important, but I tried to install the package by following the instructions. However the first cmake command failed due to a missing dependency of [lcov](https://github.com/linux-test-project/lcov), which I don't have on my old Linux distribution. Maybe you'd like to be aware of that... After installing `lcov`, it worked.

**Comment by tvatter** [comment]
Actually, there is no dependency on lcov whatsoever, except that we use it to analyze our code coverage. 

Therefore, I totally agree with you, I just made a PR to change this (#201), namely the CODE_COVERAGE flag will be "OFF" by default.
