### ISSUE TITLE
Parallel computing

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/vinecopulib#219]
I think that now we have all the most important features, we can start thinking about parallelizing the computations. I personally like OpenMP, because it requires only minimal changes and is pretty much standard in scientific computing. Alternative would be to use STL threads but that would require quite a bit of refactoring I think.

**Comment by tvatter** [comment]
The issue with OpenMP is that Apple-provided clang does not support it. Also, I'm not sure how good this is on windows (e.g., I don't see Visual Studio listed [here](http://www.openmp.org/resources/openmp-compilers/)). 

I was also looking at [this comparison](http://pawangh.blogspot.com/2014/05/mpi-vs-openmp.html). Essentially, my conclusion is that MPI is more flexible (e.g., works with distributed memory too) and often more performant, but also much harder to use.

**Comment by tnagler** [comment]
Ah I thought clang is supporting it now, but apparently that's only llvm-clang. Well then good bye OpenMP ;)

**Comment by tvatter** [comment]
To avoid having to stupidly search the closed issues again: #13

**Comment by tnagler** [comment]
The fitting functions are no parallelized with a thread pool based on `std::thread`, see #240.
