### ISSUE TITLE
fix FitControlsBicop FitControlsVinecop usages in README file

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#228]
needs an update to match addition of nonparametric_method

**Comment by tnagler** [comment]
Not sure what you mean, it contains:

>* `std::string nonparametric_method` describes the degree of the density 
approximation for the transformation kernel estimator. It can take 
`constant`, `linear` and `quadratic` (default) for approximations of 
degree zero, one and two.

**Comment by slayoo** [comment]
sorry, the code samples include calls to old fit controls ctors

**Comment by tnagler** [comment]
was fixed by f029af2.
