### ISSUE TITLE
TLL0 leftover

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#229]
https://github.com/vinecopulib/vinecopulib/blob/dev/src/bicop/family.cpp#L28

**Comment by tnagler** [comment]
How should we name this @tvatter? Suggestions
- [ ] tll
- [ ] Kernel
- [ ] Transformation kernel
- [ ] Local likelihood
- [ ] Transformation local likelihood

**Comment by tvatter** [comment]
While we're on the naming:

- [ ] The vector of BB families should be called bb.
