### ISSUE TITLE
Triangular arrays

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#358]
Two things:

1. Shouldn't we put the class in misc? I lost 3mn looking for it in the various branches before remembering that it was in vinecop.
2. Performance-wise, using a single vector (e.g. of length d * (d - 1) / 2 for untruncated arrays) would probably be better. Also, since we only access the elements through the operators `()` and `[]`, we could implement this change with very little effort.

**Comment by tnagler** [comment]
agreed on both

**Comment by tnagler** [comment]
Ok, we'll do 1. and postpone 2. for later (or never).

**Comment by tvatter** [comment]
Alright, closing for now, we can revisit 1. later if we feel like it.
