### ISSUE TITLE
Partially specified structures

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#360]
I think that adding a method allowing to "complete partially specified structures" would be useful. For instance, I'm thinking about where

- only the first tree is "known" manually (i.e., to use Dissman to select the rest),
- ones "knows" the structure but wants to select the optimal threshold/truncation level.

**Comment by tnagler** [comment]
Yeah that first case came up a couple of times already. Shouldn't be to hard with our new vine array representation. The second case is already available I think (select_families() with appropriate FitControls).

**Comment by tvatter** [comment]
OK, since this case came up twice recently (for the eecop and bigpcc projects), I'll finally get to this.

I was planning on essentially:

- adding a `size_t partial` data member to `FitControlsVinecop` allowing to specify from which tree the structure selection would start
- creating a `Vinecop::select_partial` function that would do something in between `Vinecop::select_all` and `Vinecop::select_families`

Also, `partial` would be used for the constructors taking `matrix` or `order` + `struct_array`.

The "issue" is that, design-wise, there will be a lot of redundancy, as `select_all` and `select_families` become special cases of `select_partial`. As such, it might make more sense to have a single `select` function with different behaviors given the value of `partial`. This is especially obvious for constructors, given that the one using `select_families` and the one using `select_partial` couldn't have the same arguments...

Thoughts?

**Comment by tnagler** [comment]
A few random thoughts:
- A unified `select()` method as  sounds like a very good idea. We can soft deprecate the specialized methods.
- Idea for the API: it would be convenient to provide a partial structure as a truncated `struct_array`. We could do `bool partial` and complete everything above the `trunc_lvl`. We still have a `trunc_lvl` slot in `FitControls` for setting a truncation level.
