### ISSUE TITLE
CMake is not able to find `wdm`

### ISSUE THREAD

**Issue by kdheepak** [vinecopulib/vinecopulib#388]
```
cmake -DVINECOPULIB_SHARED_LIB=ON ../ 
```

I get the following error when I run the above:

```
CMake Error at cmake/findDependencies.cmake:6 (find_package):
  By not providing "Findwdm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "wdm", but
  CMake did not find one.

  Could not find a package configuration file provided by "wdm" with any of
  the following names:

    wdmConfig.cmake
    wdm-config.cmake

  Add the installation prefix of "wdm" to CMAKE_PREFIX_PATH or set "wdm_DIR"
  to a directory containing one of the above files.  If "wdm" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/$USER/GitRepos/vinecopulib/build/CMakeFiles/CMakeOutput.log".
```

Suggestions on how to debug?

**Comment by tvatter** [comment]
Hi,

You probably don't have wdm install, please follow the guidelines there:

https://github.com/tnagler/wdm

Then, if the message happens again, let us know.

**Comment by kdheepak** [comment]
Thanks for the quick reply! I cloned `wdm` and was able to run `cd wdm; mkdir build; cd build; cmake ..; make` successfully. However, when I run the cmake command for `vinecopulib`:

`cmake -DVINECOPULIB_SHARED_LIB=ON -Dwdm_DIR=../wdm/build/generated/ ..`

I still get the same error:

```
cmake -DVINECOPULIB_SHARED_LIB=ON -Dwdm_DIR=../wdm/build/generated/ ..
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
-- Eigen3 version:
-- Boost version: 1.68.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error at cmake/findDependencies.cmake:6 (find_package):
  By not providing "Findwdm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "wdm", but
  CMake did not find one.

  Could not find a package configuration file provided by "wdm" with any of
  the following names:

    wdmConfig.cmake
    wdm-config.cmake

  Add the installation prefix of "wdm" to CMAKE_PREFIX_PATH or set "wdm_DIR"
  to a directory containing one of the above files.  If "wdm" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/$USER/GitRepos/vinecopulib/build/CMakeFiles/CMakeOutput.log".
```

What am I missing?

**Comment by tvatter** [comment]
Did you install `wdm` through `sudo make install` as specified there?

**Comment by kdheepak** [comment]
I don't have sudo permissions on the machine. So I didn't run the install
step. Why wouldn't cmake pick up the headers?

**Comment by tvatter** [comment]
Because you didn't install them... Can you try running `make install` without sudo?

**Comment by tvatter** [comment]
If you can't install in the default place, then you could install `wdm` in a custom location and then tell `cmake` where to look for this custom install:

* `cmake .. -DCMAKE_INSTALL_PREFIX=my/custom/location` and then `make install` for `wdm`.
* `cmake .. -DVINECOPULIB_SHARED_LIB=ON -DCMAKE_PREFIX_PATH=my/custom/location` for `vinecopulib`.

**Comment by kdheepak** [comment]
Thanks! That resolved it! However, now I'm getting a different error:

```
[ 53%] Linking CXX shared library libvinecopulib.dylib
[ 53%] Built target vinecopulib
Scanning dependencies of target src_test
[ 55%] Building CXX object test/src_test/CMakeFiles/src_test.dir/kernel_test.cpp.o
[ 58%] Building CXX object test/src_test/CMakeFiles/src_test.dir/parbicop_test.cpp.o
[ 58%] Building CXX object test/src_test/CMakeFiles/src_test.dir/vinecop_test.cpp.o
In file included from /Users/dkrishna/GitRepos/vinecopulib/test/src_test/vinecop_test.cpp:7:
/Users/dkrishna/GitRepos/vinecopulib/test/src_test/include/vinecop_test.hpp:11:10: fatal error: 'rscript.hpp' file not found
#include "rscript.hpp"
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [test/src_test/CMakeFiles/src_test.dir/vinecop_test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [test/src_test/CMakeFiles/src_test.dir/all] Error 2
make: *** [all] Error 2
```

Is there a way to compile it without `rscript` dependencies?

**Comment by tvatter** [comment]
Yes, totally, R and VineCopula are only required for the unit tests. You can run `cmake` with `-DBUILD_TESTING=OFF`.

**Comment by kdheepak** [comment]
Great! That worked! I had to build Eigen from source too, but now I have a shared library.

**Comment by TY-Cheng** [comment]
Hi! had similar experience here, after git cloning `wdm` and be the `build` there to `cmake ..`
`cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at build/googletest-src/googletest/CMakeLists.txt:22 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'gtest_disable_pthreads'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python: C:/Python39/python.exe (found version "3.9.7") found components: Interpreter
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
--
-- ------------------ General configuration for wdm 0.2.2
--
-- CMAKE_SYSTEM_PROCESSOR=        AMD64
-- Generator=                     Visual Studio 15 2017
-- CMAKE_SYSTEM_VERSION=          10.0.19043
-- CMAKE_CXX_COMPILER_ID=         MSVC
-- CMAKE_CXX_COMPILER=            C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- CMAKE_CXX_COMPILER_VERSION=    19.16.27045.0
-- CMAKE_BUILD_TYPE=
-- CMAKE_CXX_FLAGS=               /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj
-- CMAKE_CXX_FLAGS_DEBUG=         /MDd /Zi /Ob0 /Od /RTC1
-- CMAKE_CXX_FLAGS_RELEASE=       /MD /O2 /Ob2 /DNDEBUG
--
-- BUILD_TESTING=                 ON
-- CODE_COVERAGE=                 OFF
--
-- Configuring done
-- Generating done
-- Build files have been written to: D:/OneDrive - National University of Singapore/vinecopulib/wdm/build`

However, after `make install` it says:

`make: *** No rule to make target 'install'.  Stop.`

tried git bash, powershell, and cmd on windows. Would you suggest a proper way? 
Thx.

**Comment by tnagler** [comment]
Could you try `cmake --build . --target install` instead of `make install`?

**Comment by TY-Cheng** [comment]
Thank you! I changed from `git bash` to `MSYS2` and it works for `make install` in `/wdm/build`

![image](https://user-images.githubusercontent.com/14033617/140019067-0212647a-fbd1-40b0-a341-6a8c52d0e592.png)

However, when I tried `make install` in `/vinecopulib/build` it says:

![image](https://user-images.githubusercontent.com/14033617/140019530-8b06e51a-f6e5-493a-b3c1-7860947f3391.png)

Any suggestions on Terminal/Compiler/Boost config for windows users? Thx.

**Comment by tnagler** [comment]
This looks like an issue with your boost installation. Unfortunately, this stuff is always a huge headache on windows and we've spent countless days fixing issues caused by an update of our continuous integration servers. 

The best advice I can give is to look what we did [there](https://github.com/vinecopulib/vinecopulib/blob/ae34d56408437e6eeacec40a51a8fa8dac378672/.github/workflows/continuous_integration.yml). This should be the part relevant for windows:

``` bash
# shell: bash

# Set environment variables and path
echo "CMAKE_GEN_PLAT=x64" >> $GITHUB_ENV
echo "WDM_CMAKE_DIR=C:\projects\wdm-install\lib\cmake" >> GITHUB_ENV
echo "EIGEN3_INCLUDE_DIR=C:\projects\eigen-3.3.7" >> $GITHUB_ENV
echo "D:\a\vinecopulib\vinecopulib\release" >> $GITHUB_PATH
echo "D:\a\vinecopulib\vinecopulib\release\Release" >> $GITHUB_PATH
if [ "${{ matrix.cfg.platform }}" == "x64" ]; then
  echo "CMAKE_GEN_PLAT=x64" >> $GITHUB_PATH
else
  echo "CMAKE_GEN_PLAT=Win32" >> $GITHUB_PATH
fi

# Install other dependencies
cmd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.cfg.platform }}
choco install boost-msvc-14.1
choco install wget
wget http://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip
7z x eigen-3.3.7.zip -o"C:\projects" -y > nul

Rscript -e "install.packages('VineCopula', repos='http://cran.rstudio.com/')"

git clone https://github.com/tnagler/wdm.git
cd wdm && mkdir build && cd build
cmake .. -DCMAKE_GENERATOR_PLATFORM="${CMAKE_GEN_PLAT}" -DCMAKE_INSTALL_PREFIX="C:\\projects\\wdm-install"
echo "PATH_ORIG=${PATH}" >> $GITHUB_ENV
cmake --build . --config Release --target install
cd ../..

# Compile the debug version
cmake .. -DCMAKE_GENERATOR_PLATFORM="${CMAKE_GEN_PLAT}" -DCMAKE_INSTALL_PREFIX="C:\\projects\\vinecopulib-debug" -DEIGEN3_INCLUDE_DIR="${EIGEN3_INCLUDE_DIR}" -DCMAKE_PREFIX_PATH="${WDM_CMAKE_DIR}"
cmake --build . --config Debug

# Install the release version and test the install
cmake .. -DCMAKE_GENERATOR_PLATFORM="${CMAKE_GEN_PLAT}" -DEIGEN3_INCLUDE_DIR="${EIGEN3_INCLUDE_DIR}" -DCMAKE_PREFIX_PATH="C:\\projects\\vinecopulib-release;${WDM_CMAKE_DIR}" 
cmake --build . --config Release
"../bin/Release/main.exe"
```
In the past, we used appveyor builds for windows. You can still find [old versions](https://github.com/vinecopulib/vinecopulib/blob/c53aa339af690188528f65cd668d5e70b31549ae/appveyor.yml) of the config file using a combination of `cmd` and (mostly) PowerShell.
