### ISSUE TITLE
Handling of discrete variables

### ISSUE THREAD

**Issue by tnagler** [vinecopulib/vinecopulib#396]
- discrete mass could be detected by searching for non-unique observations (although this behavior should probably be disabled by default)
- the support of the variables needs to be stored in the object
- the Bicop likelihood can be easily implemented with what we have already ([formulas](https://arxiv.org/pdf/1705.08310.pdf) on last display of p4)

**Comment by jd-lara** [comment]
Are you planning on supporting something with mixed discrete and continuous margins?

**Comment by tnagler** [comment]
yes!

**Comment by jd-lara** [comment]
Are you implementing nonparametric D-vine quantile re-gression?

**Comment by tnagler** [comment]
probably not with a C++ frontend, but the [vinereg](https://github.com/tnagler/vinereg) R-package will also benefit from the changes that we make here.

**Comment by tnagler** [comment]
See #454
