### ISSUE TITLE
cannot open source file "wdm/eigen.hpp"

### ISSUE THREAD

**Issue by zhoustgithub** [vinecopulib/vinecopulib#447]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'wdm/eigen.hpp': No such file or directory	

I use the Visual studio 2015. However, "#include <wdm/eigen.hpp>" gives the above error.
How can I fix it? Thanks.

**Comment by tvatter** [comment]
I think that you need to install wdm (https://github.com/tnagler/wdm). It is header only, so you can probably just clone the repo and let cmake where to find the headers.

**Comment by zhoustgithub** [comment]
Thank you very much. It works after install wdm. But other problems are encountered. I finally found that the root of these problems is that the version of boost (1.58) is lower. The error is corresponding to this statement "Unknown compiler version - please run the configure tests and report the results". Then, I use the latest (1.70), the examples run correctly. Thanks again.

**Comment by tvatter** [comment]
Glad that it worked. I'm surprised by the boost issue though. I thought that it worked with version 1.56.

**Comment by tnagler** [comment]
Boost  1.56 worked on linux at least.

We use boost 1.58 for our continuous integration tests on travis, so there must be some incompatibility with visual studio (although the 1.58 release notes state "Added Visual Studio 2015 detection"). 

Not sure how to proceed. Maybe we should change the requirements to:
> Boost 1.56 (or later; MSVC may require are more recent version)

**Comment by tnagler** [comment]
Closing this, since there doesn't seem to be an issue anymore.
