### ISSUE TITLE
is the expression of pair-copula index right? R-vine matrix notation

### ISSUE THREAD

**Issue by zhoustgithub** [vinecopulib/vinecopulib#448]
Denoting by M[i, j] the matrix entry in row i and column j, the pair-copula index for edge e in tree t of a d dimensional vine is (M[d - 1 - t, e], M[t, e]; M[t - 1, e], ..., M[0, e]).

Does above expression of pair-copula index given in the website documents have to be modified to (M[d - 1 - e, e], M[t, e]; M[t - 1, e], ..., M[0, e])?

**Comment by zhoustgithub** [comment]
another issue: the 3-dimensional Rvine matrix
` 1,1,1`
`2,2,0`
`3,0,0`
I get its structre array (using get_struct_array() function difined in both RVineStructure and Vinecop), it is
`3,3`
`2`
Is it right?
I think it should be
`1,1`
`2`
according the definition of structure array ginven in the website document (i.e. all elements above the diagonal in the R-vine array).  did i miss anything?

**Comment by tnagler** [comment]
You are right, it should be `(M[d - 1 - e, e], M[t, e]; M[t - 1, e], ..., M[0, e])`.

Regarding the other issue: What you get is the structure array in natural order. From the [docs](https://vinecopulib.github.io/vinecopulib/classvinecopulib_1_1_r_vine_structure.html) :
> An R-vine array is said to be in natural order when the anti-diagonal entries are 1, ..., d  (from left to right). [...] Since most algorithms work with the structure in natural order, this is how RVineStructure stores the structure internally.

However, this (admittedly unintuitive) behavior is going to change the in the next version. We already made the changes in the `dev` branch, see #437 and #439.

**Comment by zhoustgithub** [comment]
Thank you very much!
