### ISSUE TITLE
Documentation of the tools_stats namespace

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#450]
Maybe this should be documented (in the html doc I mean), since to_pseudo_obs and the random numbers generators can be useful to users.

**Comment by tnagler** [comment]
[It's there](https://vinecopulib.github.io/vinecopulib/namespacevinecopulib_1_1tools__stats.html) (click on "Classes"), but not prominent enough. Let's keep this open and revise the manual before the next release.

**Comment by tvatter** [comment]
Oh ok, yeah then probably it would be nice to be able to find it without clicking on classes, because I did not ^^

**Comment by tnagler** [comment]
solved by #461. The namespaces will be visible in the navbar as soon as we re-generate the docs.
