### ISSUE TITLE
Remove unnecessary whitespace characters in JSON files

### ISSUE THREAD

**Issue by dmey** [vinecopulib/vinecopulib#505]
In the current implementation to write the copula object into a JSON file, whitespace characters are saved. Removing them could save large amount of space. In my case (object size > 2 GB), removing them cut the size in half.

**Comment by tvatter** [comment]
Interesting! The current implementation uses [boost property trees](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree.html), which can be exported in a number of data formats that can be represented by such a tree, including XML, INI, and JSON.

It seems like the [XML can be trimmed from the whitespace](https://www.boost.org/doc/libs/1_65_1/doc/html/property_tree/parsers.html), but there is nothing we can do for JSON files.

Saving as XML will definitely be included in the next release!

**Comment by tvatter** [comment]
Done #539
