### ISSUE TITLE
High memory usage when loading JSON files

### ISSUE THREAD

**Issue by dmey** [vinecopulib/vinecopulib#506]
When loading a large (> 2 GB but cut to 1 GB after removing whitespace characters -- see #505) copula object from JSON , vinecopulib used 30 GB of memory. Is this expected? And if so what is the reason for this? This may lead to a very slow performance when swap is used.

**Comment by tvatter** [comment]
I am unsure what happens. Are you using the C++ library? If yes, is the memory use happening when doing creating the boost property tree (see answers to your other two PRs) or when it's actually saved to json? If not, we need to investigate, I've not noticed such a thing.

**Comment by dmey** [comment]
I am actually using the python bindings but the bottleneck is in C++. This is only for loading. I can share the file with you if you'd like it's only a couple of hundred of MBs compressed.

**Comment by tvatter** [comment]
I see, I will investigate. Currently, the routines allowing to load from JSON are doing two things:

1. Use stuff boost to read the JSON an create the property tree:

```
inline boost::property_tree::ptree
json_to_ptree(const char* filename)
{
  boost::property_tree::ptree output;
  boost::property_tree::read_json(filename, output);
  return output;
}
```

2. Create the object from the property tree using custom conversions which are straightforward loops.

If the memory usage comes from the first step, there is not much we can do. But if it comes from the second step, maybe there is hope.

**Comment by tvatter** [comment]
Since there hasn't been an answer, I'm going to assume that this isn't a problem anymore? Don't hesitate to reopen otherwise.
