### ISSUE TITLE
about the CDF of the kernel vinecopula 

### ISSUE THREAD

**Issue by laten21** [vinecopulib/vinecopulib#548]
Dear Nagler

I need help in R, please. 
usually, any package of any distribution in R contains three commands such as rname, dname and pname. I found a package called kdevine https://github.com/tnagler/kdevine

and it has dkdevinecop and rkdevinecop but it doesn't have the option pkdevinecop (the CDF). I tried to write it like this but it is wrong, could you see it, please

Regards

library(kdevine)
library(kdecopula)

data(wdbc)

fit <- kdevine(wdbc[, 5:7], xmin = rep(0, 3))
f<-dkdevine(wdbc[, 5:7], fit)

for(i in 1:length(f)){
 p<-sum(dkdevinecop(c(wdbc[, 5],wdbc[,6],wdbc[,7]),fit))
 }
  print (p)

**Comment by tnagler** [comment]
This is the github page of the vinecopulib C++ library. You can ask questions about the kdevine library at kdevine's github page.
