### ISSUE TITLE
Independence copula causes deserialization to fail

### ISSUE THREAD

**Issue by sdressler** [vinecopulib/vinecopulib#554]
### Summary

When an Independence copula is present, and the user serializes the structure to JSON, loading will result in an exception. I could observe it on version 0.6.1.

### Reproduction

1. Create a model with an Independence copula
2. Serialize the structure to JSON
3. Load the structure again from the JSON file

### Observation

Deserialization throws an exception: `[json.exception.type_error.302] type must be array, but is null`

### Expectation

Deserialization should work just fine.

### Assumed root cause

Tracked this down until here: https://github.com/vinecopulib/vinecopulib/blob/ae34d56408437e6eeacec40a51a8fa8dac378672/include/vinecopulib/misc/tools_serialization.hpp#L91
This breaks because `input["data"]` is null here. `json_to_triangular_array` might be affected as well. I can provide a PR with a fix proposal, if desired.

**Comment by tnagler** [comment]
I think this has been fixed already in the [`dev`](https://github.com/vinecopulib/vinecopulib/tree/dev) branch via #546. Could you pull from `dev` and confirm?

**Comment by sdressler** [comment]
Yep, looking good. Thanks.

**Comment by sdressler** [comment]
Found another case with [this JSON](https://pastebin.com/yv8RecSq). Breaks during with an exception on dev: `Exception: [json.exception.type_error.302] type must be number, but is null`. I am trying to debug where it comes from.

**Comment by sdressler** [comment]
Fix proposal:

```diff
diff --git a/include/vinecopulib/misc/tools_serialization.hpp b/include/vinecopulib/misc/tools_serialization.hpp
index d9ffdd3..d04fb97 100644
--- a/include/vinecopulib/misc/tools_serialization.hpp
+++ b/include/vinecopulib/misc/tools_serialization.hpp
@@ -91,7 +91,11 @@ json_to_matrix(const nlohmann::json& input)
 
   Eigen::MatrixXd matrix;
   if (!input["data"].is_null()) {
-    std::vector<double> vec = input["data"];
+    std::vector<double> vec;
+    for (auto it : input["data"].items()) {
+        const auto val = it.value();
+        vec.push_back(val.is_null() ? 0.0 : val.get<double>());
+    }
     matrix = Eigen::MatrixXd::Map(&vec[0], rows, cols);
   } else {
     matrix = Eigen::MatrixXd();
```

**Comment by tnagler** [comment]
I guess the fix would work, but that particular JSON snippet should never have been written. Since the log-likelihood is 0 and no parameter is set, this seems to be an independence copula - the family is indicated as Gaussian. Don't immediately see how that can happen. Anything notable on how you fit the model?

**Comment by sdressler** [comment]
I see. My approach uses joint probabilities over a bin-mapping converted to ECDF per column. Before calculating joint probabilities, the columns are sorted by their distinct count. Not sure what would cause an Independence copula, but I can think of two extreme cases after encoding:

- The column distribution becomes close to constant
- The column distribution becomes close to uniform

I am not excluding these cases before sending them to the library. Maybe that causes this specific problem. I'd need to find the column and investigate the data. Is it possible to derive the column position from the model? I didn't read too much of it so far...

**Comment by tnagler** [comment]
What's the `FitControls` you use?

**Comment by sdressler** [comment]
```c++
    const auto bicopControls = vinecopulib::FitControlsBicop(
        vinecopulib::bicop_families::one_par
      , "itau"      // parametric_method,
      , "quadratic" // nonparametric_method
      , 1.0         // double nonparametric_mult = 1.0
      , "mbicv"     // selection_criterion
      , Eigen::VectorXd()
                    // weights
      , 0.9         // psi0
      , true        // preselect_families
      , numThreads  // num_threads
    );

    const auto vinecopControls = vinecopulib::FitControlsVinecop(
        bicopControls
      , std::numeric_limits<size_t>::max()
                    // trunc_lvl
      , "tau"       // tree_criterion
      , 0.0         // threshold
      , true        // select_trunc_lvl
      , false       // select_threshold
      , false       // show_trace
      , numThreads  // num_threads
    );
```

---
Off-topic, but your tips helped me to get processing time from 3 days down to 1 hour. Many thanks, should by you a ☕ , or multiple 😉

**Comment by tnagler** [comment]
It's really weird. The pair-copulas are serialized here: https://github.com/vinecopulib/vinecopulib/blob/ae34d56408437e6eeacec40a51a8fa8dac378672/include/vinecopulib/bicop/implementation/class.ipp#L128-L141

For the parameters, `matrix_to_json()` is called:
https://github.com/vinecopulib/vinecopulib/blob/ae34d56408437e6eeacec40a51a8fa8dac378672/include/vinecopulib/misc/tools_serialization.hpp#L25-L39

The iterator business should be fine as long as Eigen behaves as expected. The matrix dimensions are stored in `shape` and should be `[1, 1]` in your example. Then  `matrix.size()` should return `1` and the loop should fetch and write one element from the `matrix` (which cannot contain `null`). 

We could try without the iterator though and make the column/row loops more explicit. Could you run the same model with branch [fix-json](https://github.com/vinecopulib/vinecopulib/tree/fix-json)?

---------------

P.S.: Very glad I could help! Making vine copula models computable for such large problems is one of the main motivations for this library, so I count this as a success story.

I'll take the coffee when you're in Munich some time. But I already appreciate your effort to help improving the library. Also always happy to hear how and for what purpose people are using it, so feel free to shoot me an email about you modeling ;)

**Comment by sdressler** [comment]
> [...]
> 
> The iterator business should be fine as long as Eigen behaves as expected. The matrix dimensions are stored in `shape` and are `[1, 1]` in your example. Then `matrix.size()` should return `1` and the loop should fetch and write one element from the `matrix` (which cannot contain `null`).
> 
> We could try without the iterator though and make the column/row loops more explicit. Could you run the same model with branch [fix-json](https://github.com/vinecopulib/vinecopulib/tree/fix-json)?

I'll try that as soon as possible (latest early next week). I hope that my input is stable enough to trigger it again. I'd debug through and try to take a sample of the input data.

I noticed that my approach could lead to issues with matrix inversion, which is why I started to remove uniformly distributed and constant-value columns. I don't apply this to post-encoding, however.

> 
> P.S.: Very glad I could help! Making vine copula models computable for such large problems is one of the main motivations for this library, so I count this as a success story.

It is a success. I bought the book Claudia wrote after stumbling over Copulas and hoped to have some library at hand after I tried to implement a single n-dimensional Copula on my own. It worked for some basics. This library here is just so much better, however.

> I'll take the coffee when you're in Munich some time. But I already appreciate your effort to help improving the library. Also always happy to hear how and for what purpose people are using it, so feel free to shoot me an email about you modeling ;)

I'll check with my employer how much I can share and send you an e-mail. I am also investigating more performance details. As you noticed, I disabled the Student Copula because this is the one consuming the most time (even with `itau`). I saw slowness coming from boost and other places but didn't investigate further.

**Comment by tnagler** [comment]
> I noticed that my approach could lead to issues with matrix inversion ...

There's no matrix inversion on our side.
> ... I started to remove uniformly distributed and constant-value columns. 

Constant columns you should definitely exclude, since (mathemattically speaking) their probability density does not exist and (practically speaking) modeling their "distribution" is useless. 

Uniformly distributed columns are no problem. On the contrary, all columns *must* be approximately uniformly distributed when you pass them to our library, because that's what a copula model assumes. If they are not, you need to do some marginal modeling first or at the very least apply [`to_pseudo_obs()`](https://vinecopulib.github.io/vinecopulib/namespacevinecopulib_1_1tools__stats.html#a33d38ef57a785252e2fe0684a8627ce8) and an appropriate back-transformation later.  

The Student copula is orders of magnitude slower than others in `bicop_families::itau` because it requires optimization of the degrees-of-freedom parameter. I just double-checked and realized that the  degrees-of-freedom parameter is still optimized at full accuracy (opposed to what I did in [VineCopula](https://github.com/tnagler/VineCopula/blob/main/R/BiCopEst.R)) . That level of accuracy is probably unnecessary in most applications and I'm just waiting for someone to convince me to relax it.
