### ISSUE TITLE
get_disc_cols

### ISSUE THREAD

**Issue by FLBuchner** [vinecopulib/vinecopulib#591]
Hi,

https://github.com/vinecopulib/vinecopulib/blob/258eb2d7758ce067ee7d53789067f0d3ebbb9375/include/vinecopulib/vinecop/implementation/tools_select.ipp#L88

I think this should be

disc_cols[i] = ++disc_count;

First increment disc_count, then set value in disc_cols.

Best,
Ferdinand

**Comment by tnagler** [comment]
I don't think so. For example, in
[`base_tree[e].hfunc1_sub = data.col(d_ + disc_cols[order[target] - 1]);`](https://github.com/vinecopulib/vinecopulib/blob/258eb2d7758ce067ee7d53789067f0d3ebbb9375/include/vinecopulib/vinecop/implementation/tools_select.ipp#L801)
`disc_cols` has to start with 0 for the "first" discrete column.

**Comment by FLBuchner** [comment]
Ah, I think I understand this now. data basically has as many columns as the original data + 1 column for every discrete variable. That is what happens in
https://github.com/vinecopulib/vinecopulib/blob/258eb2d7758ce067ee7d53789067f0d3ebbb9375/include/vinecopulib/vinecop/implementation/class.ipp#L1415C1-L1430C2
Then get_disc_cols works fine. Thank you
