### ISSUE TITLE
no wdm 0.2.4 tag

### ISSUE THREAD

**Issue by jschueller** [vinecopulib/vinecopulib#609]
the dev branch depends on wdm 0.2.4:
https://github.com/vinecopulib/vinecopulib/blob/dev/cmake/findDependencies.cmake#L40

but there is no such tag, so I cannot compile it:
https://github.com/tnagler/wdm/tags

**Comment by tvatter** [comment]
Is the tag really needed? Given that fetch content will download a given git commit, which corresponds to 0.2.4, I'm not sure what's missing? Plus, it seems to work locally and with the CI.

**Comment by jschueller** [comment]
it would be useful for packaging libwdm separately, plus else that find_package(wdm) is useless without it

**Comment by tvatter** [comment]
I'll let @tnagler push the tag to the wdm repo. I believe we've used v0.2.2 (v, same as in vinecopulib), so it would be v0.2.4, is that an issue?

**Comment by tnagler** [comment]
We have a release with tag v0.2.4 https://github.com/tnagler/wdm/releases/tag/v0.2.4

**Comment by jschueller** [comment]
thanks
