### ISSUE TITLE
Need for speed

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#69]
Currently, the speed of the library is comparable to `VineCopula` at best (e.g., for the pdf evaluation of a vine or the selection of a bivariate copula). I open this issue in order to list the potential areas of improvements.

- [ ] Avoid copying the data all the time with `cut_and_rotate`
- [ ] Implement the analytical gradients
- [x] Use something like `binaryExpr` to compute stuff for Archimedean families instead of calling `unaryExpr` for the generator and its derivatives separately.

Any ideas?

**Comment by tnagler** [comment]
Agree on all three suggestions. If we do this, we should already be faster than VineCopula (because it avoids copies in the vine pdf).

**Comment by tvatter** [comment]
As suggested in #176, we can use a method faster than the bisection to invert functions to speed-up the simulations.

**Comment by bodashtart** [comment]
Guys, can you provide examples where VineCopula performs better at present? We can look more into them and build upon them next week while we're looking into performance and benchmarking (I tried several examples fitting to financial data and simulating, and in all cases the new library was faster than VineCopula).

**Comment by tnagler** [comment]
I remember that `vinecopulib::Vinecop::pdf()` was slower than `VineCopula::RVinePDF()` when the number of evaluation points is large. That was the only "issue" that I found when I was doing some experimental benchmarking two months ago.

**Comment by tnagler** [comment]
I'll close that for now, gradients are still pending in #377
